### ISSUE TITLE
Research wordpress themes.

### ISSUE THREAD

**Issue by JessaWitzel** [JessaWitzel/dearhrc.us#1]
We want something clean and easy to read that allows us to feature a blogroll of letters to HRC. We need a header and a toolbar. Easy. :)

**Comment by JezzabellGem** [comment]
These are the themes we've collected for discussion so far:

https://wordpress.org/themes/beautytemple/

https://wordpress.org/themes/concept-lite/

https://wordpress.org/themes/activello/

https://wordpress.org/themes/nisarg/

http://www.ydesignservices.com/live/?theme=comley-free&category=free-wordpress-themes  

https://themeisle.com/demo/?theme=Lawyeria  

https://wordpress.org/themes/onepress/

**Comment by JessaWitzel** [comment]
I like Comley the best. It has the simplicity, is responsive, and will feature the letters most. I like Concept-Lite second.

**Comment by JezzabellGem** [comment]
I am agree about Comley, and I also love Nisarg. Since you have WP installed now, I might install both of the themes that you like, create a few of the pages, and put in some fake content. Switch between themes, and let's see which we prefer. Thoughts?

**Comment by JezzabellGem** [comment]
Closing this, because we decided on Comley. I have downloaded it.
