### ISSUE TITLE
Research Submission Plugin

### ISSUE THREAD

**Issue by JessaWitzel** [JessaWitzel/dearhrc.us#4]
Needs: 

- Can receive a submission
- Can give submitter feedback and request changes
- Can receive new edits w/priority
- Can notify sender when submission has been posted
- Requires valid email for submission
- Autoformats submissions into blog post
- Pushes to blog

**Comment by JezzabellGem** [comment]
I didn't see the above comment before writing this, so there are some overlaps!

Ultimately, what I think we're looking for should contain the following:

A submission form with a simple rich text widget that will let people emphasize things like bold, italics, linked or underlined content easily, that will then translate to our themed formatting once published. (using markdown, maybe?)

It should put those submissions into a database queue for review, where we can comment about changes/errors that need to be made before publishing, and have an admin interface for doing so.

Also, they're going to need to have an account with the site for this work, so a sign in with Google or Facebook option is easiest...I think.

**Comment by JezzabellGem** [comment]
A few links to some plug ins that have at least some of the things we're looking for. 

https://wordpress.org/plugins/wp-github-sync/

https://wordpress.org/plugins/heypublisher-submission-manager/  (hasn’t been rated, but 60 people installed it)

https://wordpress.org/plugins/front-end-publishing/

**Comment by JezzabellGem** [comment]
Since there was no WP plug in hat addressed everything we need, I think custom building the microsite is our best option. I've submitted a plan and issues for this.

**Comment by JessaWitzel** [comment]
wordpress has a user called contributor:
Contributor – Can write posts but cannot publish them. Instead, they need to submit their posts for review.

It seems like the review is in a dated queue just like all other blog posts I believe, so it would prioritize based on date started.

It seems like perhaps we can just use the standard wordpress functionality. Have people who want to submit sign up on our site as a contributor: http://www.wpbeginner.com/beginners-guide/how-to-allow-user-registration-on-your-wordpress-site/

That requires an email to sign in, will autoformat everything into a blog post, will submit for review, allow us to edit, and possibly queue everything up properly. We can test to see how the queue works and whether we can give it back for feedback. I'll try to test that tonight.
